variables:
  # no need to fetch LFS files
  GIT_LFS_SKIP_SMUDGE: "1"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  script:
    - mkdir public
    - cp index.html public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
